### PR TITLE
db host configuration

### PR DESCRIPTION
**Pull request by sgrimault**
Allow DB hostname configuration from global settings and remove hardcoded 'geonatdbhost'

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
Interesting commit @sgrimault and glad to get a PR from you in GeoNature ! 
@gildeluermoz knows better than me about how he set hosts in GeoNature and why he used this alias. 
It is used at other places and in documentation : https://github.com/PnEcrins/GeoNature/search?utf8=%E2%9C%93&q=geonatdbhost

Maybe a way to do would be to set `$db_host` to `geonatdbhost` by default in `settings.ini.sample` so it would work the actual way by default but as a setting people could change it. 

PS : The PR also include all our recent commits in develop.

**Comment by sgrimault** [comment]
I'm starting from 'develop' as default branch using git flow ('master' should be considered for release versions). I can close and create a new PR from 'master' if you want ?

**Comment by camillemonchicourt** [comment]
Yes we work in develop and merge in master when we are ready to release a new version. So I think it is good as you did. Thanks.

**Comment by camillemonchicourt** [comment]
Interesting PR, not sure why it was closed ?

**Pull request closed without merging**
